services:
  app:
    build: .
    ports:
      - "8080:80"
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: mobile
    develop:
      watch:
        - action: sync
          path: .
          target: /var/www/html
  
  db:
    image: mysql:8.0
    volumes:
      - todo-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: mobile

volumes:
  todo-mysql-data:
