apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-app-deployment
  labels:
    app: php-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: php-app
  template:
    metadata:
      labels:
        app: php-app
    spec:
      containers:
      - name: php-app-container
        image: codepreet/docker_php_multi_containers:03
        envFrom:
          - configMapRef:
              name: php-app-config
        ports:
        - containerPort: 80
          name: php-app-port
